### ISSUE TITLE
对目前 wrapper 完成度的疑问

### ISSUE THREAD

**Issue by Ferry-200** [realth000/taglib_ffi#1]
看了下 src 目录下的 wrapper，好像是只完成了统一的 tag 读取和 id3v2 的细分读取。其他的比如 flac 的 vorbis comment 和 wav 的 riff 读取好像并没有包装。请问有考虑继续完善下去吗？

**Comment by realth000** [comment]
会做，近期我另一个音乐项目开始做了，也有读写音频元数据的需求，这个仓库大概半个月内会开始继续做。
目前完成度并不高，即使是已实现的功能，像读的标签种类、性能、windows上的中文路径、集成进项目的方式都不够好。
wav flac还有别的格式只要taglib支持就都会做，只是近期还是以id3v2为主，还有升级到taglib v2的事情。


flac的话，[metadata_god](https://pub.dev/packages/metadata_god)是个比较好的库，跨平台，速度非常快，可以试一试。

**Comment by Ferry-200** [comment]
metadata_god 就不尝试了。现在我的音乐项目 coriander player 正在使用 rust 的 lofty 库，已经有很完善的支持。只是 lofty 似乎不想像 taglib 那样支持不同编码的 wav riff info 解析（现在它只支持  utf-8 的）。我很想转向 taglib 以支持读取 utf-16 等编码的 wav 信息（它提供 StringHandler 来支持这个功能），但一直不清楚该如何自行编译 taglib，看来需要逼迫自己去学 cmake 才行。
